name: Learn CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "My first GitHub Actions workflow"